### ISSUE TITLE
Código fora do padrão Java

### ISSUE THREAD

**Issue by cacio-costa** [FelipeSilbrx/comex#2]
Felipe, o Java não usa o *snake case* (underline) como padrão de codificação. Devemos seguir o **camel case**.

E também, somente nomes de classe começam com letras maiúsculas. Aqui, há vários métodos que começam com letra maíuscula, quando deveriam ser minúsculos.

Ajusta para próxima entrega. ;)

https://github.com/FelipeSilbrx/comex/blob/c7be4bbffa6ba6ced4deb385702d154e46e044a9/src/br/com/comex/modelo/ItemPedido.java#L25

**Comment by FelipeSilbrx** [comment]
Corrigido o issue 2
