### ISSUE TITLE
Usar Set para armazenar categorias processadas

### ISSUE THREAD

**Issue by cacio-costa** [FelipeSilbrx/comex#3]
Felipão, nesse código você poderia usar um Set para armazenar as categorias já processadas. Como o Set elimina duplicados, bastaria adicionar, e usar o método `size` no fim. ;)

https://github.com/FelipeSilbrx/comex/blob/c7be4bbffa6ba6ced4deb385702d154e46e044a9/src/br/com/comex/modelo/TotalCategorias.java#L15

**Comment by FelipeSilbrx** [comment]
issue corrigido
